<a href="https://colab.research.google.com/github/KuldeepIsharwal/Machine-Learning-Basics/blob/main/KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import pandas as pd
import numpy as np

In [25]:
df = pd.read_csv('/content/breast-cancer.csv')

In [26]:
df.sample(5)

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
215,8810987,M,13.86,16.93,90.96,578.9,0.10260,0.15170,0.09901,0.05602,...,26.93,104.40,750.1,0.1460,0.4370,0.4636,0.16540,0.3630,0.10590,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.16250,0.2364,0.07678,NaN
324,89511501,B,12.20,15.21,78.01,457.9,0.08673,0.06545,0.01994,0.01692,...,21.38,91.11,583.1,0.1256,0.1928,0.1167,0.05556,0.2661,0.07961,NaN
396,90401601,B,13.51,18.89,88.10,558.1,0.10590,0.11470,0.08580,0.05381,...,27.20,97.33,675.2,0.1428,0.2570,0.3438,0.14530,0.2666,0.07686,NaN
365,901088,M,20.44,21.78,133.80,1293.0,0.09150,0.11310,0.09799,0.07785,...,26.37,161.20,1780.0,0.1327,0.2376,0.2702,0.17650,0.2609,0.06735,NaN

In [27]:
df = df.drop(columns=['id','Unnamed: 32'])

In [28]:
df.sample(5)

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
567,M,20.60,29.33,140.10,1265.0,0.11780,0.2770,0.35140,0.15200,0.2397,...,25.74,39.42,184.60,1821.0,0.16500,0.8681,0.9387,0.26500,0.4087,0.12400
490,B,12.25,22.44,78.18,466.5,0.08192,0.0520,0.01714,0.01261,0.1544,...,14.17,31.99,92.74,622.9,0.12560,0.1804,0.1230,0.06335,0.3100,0.08203
255,M,13.96,17.05,91.43,602.4,0.10960,0.1279,0.09789,0.05246,0.1908,...,16.39,22.07,108.10,826.0,0.15120,0.3262,0.3209,0.13740,0.3068,0.07957
298,B,14.26,18.17,91.22,633.1,0.06576,0.0522,0.02475,0.01374,0.1635,...,16.22,25.26,105.80,819.7,0.09445,0.2167,0.1565,0.07530,0.2636,0.07676
492,M,18.01,20.56,118.40,1007.0,0.10010,0.1289,0.11700,0.07762,0.2116,...,21.53,26.06,143.40,1426.0,0.13090,0.2327,0.2544,0.14890,0.3251,0.07625

In [29]:
from sklearn.model_selection import train_test_split

In [30]:
x_train,x_test,y_train,y_test = train_test_split(df.drop(columns=['diagnosis']),df['diagnosis'],test_size=0.2,random_state=42)

In [31]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [32]:
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [33]:
x_test

array([[-0.46649743, -0.13728933, -0.44421138, ..., -0.19435087,
         0.17275669,  0.20372995],
       [ 1.36536344,  0.49866473,  1.30551088, ...,  0.99177862,
        -0.561211  , -1.00838949],
       [ 0.38006578,  0.06921974,  0.40410139, ...,  0.57035018,
        -0.10783139, -0.20629287],
       ...,
       [-0.73547237, -0.99852603, -0.74138839, ..., -0.27741059,
        -0.3820785 , -0.32408328],
       [ 0.02898271,  2.0334026 ,  0.0274851 , ..., -0.49027026,
        -1.60905688, -0.33137507],
       [ 1.87216885,  2.80077153,  1.80354992, ...,  0.7925579 ,
        -0.05868885, -0.09467243]])

In [34]:
from sklearn.neighbors import KNeighborsClassifier

In [35]:
knn = KNeighborsClassifier(n_neighbors=5)

In [36]:
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [37]:
from sklearn.metrics import accuracy_score
y_pred = knn.predict(x_test)
accuracy_score(y_test,y_pred)

0.9473684210526315