<a href="https://colab.research.google.com/github/KuldeepIsharwal/Machine-Learning-Basics/blob/main/Naive_Bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import pandas as pd
import numpy as np

In [16]:
df = pd.read_csv('/content/play_tennis.csv')

In [17]:
df.sample(5)

  day   outlook  temp humidity    wind play
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes
6  D7  Overcast  Cool   Normal  Strong  Yes
2  D3  Overcast   Hot     High    Weak  Yes
7  D8     Sunny  Mild     High    Weak   No

In [18]:
df = df.drop(columns=['day'])

In [19]:
df.sample(5)

     outlook  temp humidity    wind play
9       Rain  Mild   Normal    Weak  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
3       Rain  Mild     High    Weak  Yes
2   Overcast   Hot     High    Weak  Yes

#in training phase naive bayes makes a lookup table which stores all the probabilities and based on the problem given it just multiplies goes to the lookup table and multiplies the probablilities

In [20]:
pd.crosstab(df['outlook'],df['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2